// Stub for /pagefind/pagefind.js used in vitest only.
// The real file is generated by pagefind at build time and does not exist during testing.
// Throwing here causes loadPagefindModule()'s catch branch to return null, which is the
// correct behaviour in any non-production environment where pagefind hasn't been built.
export {};
throw new Error("pagefind not available in test environment");
